### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SerChirag**
Added Icon to manifest.json

### CODE REVIEW

**Comment by kshitij10496** [comment]
Hey @SerChirag !
Kindly write down a brief description of the feature you are trying to achieve through this PR.

**Comment by SerChirag** [comment]
In this PR, the extension will now have a popup menu which will allow the user to bookmark the currently opened page and set a reminder for it. The user can also save it as a bookmark.
In the settings menu, user can see all the reminder he has made in the past. He is also given the choice of changing reminders.
The background scripts catches any incoming or missed alarm

**Comment by kshitij10496** [comment]
@SerChirag That sounds awesome. I will try your changes and make a review soon.
For the time being, can you squash your commits ?

**Comment by SerChirag** [comment]
Kinda having trouble doing squashing... 
Please help a bit ..

**Comment by kshitij10496** [comment]
@SerChirag 
Here are few useful reading resources on rewriting history in Git:
1. https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history
2. http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
3. https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
4. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
5. https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend

**Comment by SerChirag** [comment]
I closed this PR.. any way to open it ?

**Comment by SerChirag** [comment]
Did you try out the extension ?

**Comment by SerChirag** [comment]
Why are there no commits to my name on the leaderboard ?
Today is the last day :(

**Pull request merged**
