### PR TITLE
JQuery Bugs fixed in popup.html & popup.js

### PR DESCRIPTION
**Pull request by ritz301**
Any suggestions?

### CODE REVIEW

**Comment by kshitij10496** [comment]
`build/jquery.datetimepicker.min.js`, `build/jquery.datetimepicker.full.min.js`
What are these files ?

**Comment by ritz301** [comment]
These files are needed to use JQuery DateTimePicker.

**Comment by kshitij10496** [comment]
Okay
Have you checked the extension locally ?

**Comment by kshitij10496** [comment]
@ritz301 Merging this.
Thanks

**Comment by OrkoHunter** [comment]
I remember my first PR. The weight of this one is way too high. Great job @ritz301 !

**Comment by ritz301** [comment]
And it would not have been possible without you friends. Thanks!

**Comment by ritz301** [comment]
@kshitij10496 Yes I have checked it locally. Do you encounter any problem in that?

**Comment by kshitij10496** [comment]
Nope.
Its fine

**Pull request merged**
